// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Lg8mUGrES2zoAMkQd34K5l5-7mZ6CS8',
    appId: '1:607876304457:web:40ae559af659e021b93998',
    messagingSenderId: '607876304457',
    projectId: 'mensajeriaupv2',
    authDomain: 'mensajeriaupv2.firebaseapp.com',
    storageBucket: 'mensajeriaupv2.appspot.com',
    measurementId: 'G-9K7J7ZC4FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC6SwGkKA9SQvKqe-jX9o7R00n3uWuSGw',
    appId: '1:607876304457:android:7ca42f756b88b951b93998',
    messagingSenderId: '607876304457',
    projectId: 'mensajeriaupv2',
    storageBucket: 'mensajeriaupv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCizijfiKzZA1icVdztHSj7RYY2tnvPJAY',
    appId: '1:607876304457:ios:3e61b70ac1c862e3b93998',
    messagingSenderId: '607876304457',
    projectId: 'mensajeriaupv2',
    storageBucket: 'mensajeriaupv2.appspot.com',
    iosClientId: '607876304457-pc00dp0f9um3ki53jqm9uqs4ak0cn4od.apps.googleusercontent.com',
    iosBundleId: 'com.example.mensajeriaup2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCizijfiKzZA1icVdztHSj7RYY2tnvPJAY',
    appId: '1:607876304457:ios:c5c613cd436d360fb93998',
    messagingSenderId: '607876304457',
    projectId: 'mensajeriaupv2',
    storageBucket: 'mensajeriaupv2.appspot.com',
    iosClientId: '607876304457-bi7lme3lpptai5djki7m0mc0p3hjf8f0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mensajeriaup2.RunnerTests',
  );
}
